### ISSUE TITLE
Dynamisch erzeugte Tabellen von Kindersport und Fitness & Gesundheit auf die Hauptseite übertragen 

### ISSUE THREAD

**Issue by niklaswild** [DHBW-Website-Project/sv-mergelstetten#144]
Ich hab auf der main.css schon sozusagen das Design gemacht, ihr müsst nur noch die Klassen in eure Tabellen einbinden

**Comment by Dodomaker** [comment]
Noch sind hier leider die Tabellen als Text drinnen, übertragt einfach eure PHP Anweisung von den Unterseiten für die Dynamische Ausgabe.
