### ISSUE TITLE
Zeilenabstand, Überschriften, Tabellen Zeilenabstand und Bilder in der Mobilen Version anpassen.

### ISSUE THREAD

**Issue by Dodomaker** [DHBW-Website-Project/sv-mergelstetten#30]
Unter Punkt allgemein Zeilenabstand anpassen.
Überschriften Anpassen mit H1.
Unter Punkt allgemein Zeilenabstand.
Mobile Version Bilder anpassen (die unteren 4).

**Comment by stefan-mei** [comment]
Wurde erledigt unter dem #39 
hab es erst im nachhinein gesehen das dort ein Issue existiert.
Ein paar Kleinigkeiten werden im Nachhinein noch erledigt!
