### ISSUE TITLE
Tabelle für Termine, zusätzliche Bilder und mobile Seite anpassen

### ISSUE THREAD

**Issue by Dodomaker** [DHBW-Website-Project/sv-mergelstetten#31]
Kindersport  (Termine) in eine Tabelle packen. 
Unter jeglichen Punkt zusätzlich mit Bildern ausstatten.
In der Mobile Internetseite Bild und Schrift anpassen.

**Comment by ElMeyero** [comment]
Tabelle fertig
Bilder hinzugefügt
