### ISSUE TITLE
#94 Links im footer und navbar an .php endung anpassen

### ISSUE THREAD

**Issue by SeraphSarakiel** [DHBW-Website-Project/sv-mergelstetten#95]
Jeder sollte in seinen Untterseiten noch die ganzen Links anpassen das es ttatsächlich auch die .php und nichtt die .html seiten verlinkt. Sobald das fertig ist können wir die .html seiten löschen

**Comment by Dodomaker** [comment]
Die Änderung muss man nur im Include-Ordner in den jeweiligen Dateien durchführen

**Comment by SeraphSarakiel** [comment]
Stimmt natürlich, mb
